### ISSUE TITLE
♻️ [Tracking-Issue] Migrating Vue files to Composition API

### ISSUE THREAD

**Issue by jxn-30** [LSS-Manager/LSSM-V.4#2479]
# Migrating Vue files to Composition API

This issue keeps track on updating all Vue files to composition API. If necessary, vue files can be split into multiple files to improve readability and maintainability.

## Why?

Migrating to [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html) will allow us to have better type checking as well as an improved code-structure.
There are still some [caveats](https://v2.vuejs.org/v2/guide/migration-vue-2-7.html) while using Vue 2.7 but migration to Vue3 will be much easier on long sight.

## Progress

**Total**: (2/102)

*When migrating a file, the checkbox is to be checked and the commit reference to be added.*

* [ ] **modules** (0/78)
    * [ ] creditsextension/creditsextension.vue
    * [ ] generalExtensions/components/linkPreview.vue
    * [ ] buildingListFilter/components/preview.vue
    * [ ] overview/overview.vue
    * [ ] extendedBuilding/components/schoolingSummary.vue
    * [ ] releasenotes/releasenotes.vue
    * [ ] hotkeys/components/help.vue
    * [ ] renameFz/renameFz.vue
    * [ ] lssmaql/lssmaql.vue
    * [ ] heatmap/heatmapSettings.vue
    * [ ] statusCounter/counter.vue
    * [ ] missionHelper/missionHelper.vue
    * [ ] **support** (0/2)
        * [ ] chat.vue
        * [ ] support.vue
    * [ ] **extendedCallWindow** (0/6)
        * [ ] missionKeywords/preview.vue
        * [ ] arrSearch/arrSearchDropdown.vue
        * [ ] enhancedMissingVehicles/emv.vue
        * [ ] enhancedMissingVehicles/emvTable.vue
        * [ ] alarmIcons/preview.vue
        * [ ] collapsablePatients/collapsablePatients.vue
    * [ ] **dailyCreditsSummary** (0/2)
        * [ ] dscBadge.vue
        * [ ] dailyCreditsSummary.vue
    * [ ] **dashboard** (0/7)
        * [ ] chart-summary.vue
        * [ ] vehicle-types.vue
        * [ ] building-list.vue
        * [ ] building-types.vue
        * [ ] dispatchcenter-view.vue
        * [ ] vehicle-list.vue
        * [ ] dashboard.vue
    * [ ] **schoolingOverview** (0/3)
        * [ ] schoolingOverview.vue
        * [ ] openSchoolingTabs.vue
        * [ ] ownSchoolingTabs.vue
    * [ ] **extendedMap** (0/4)
        * [ ] mapCSSFilter/functionSlider.vue
        * [ ] mapCSSFilter/preview.vue
        * [ ] buildingComplexes/buildingComplex.vue
        * [ ] buildingComplexes/settings.vue
    * [ ] **redesign** (0/42)
        * [ ] bewerbungen.vue
        * [ ] toplist.vue
        * [ ] verband/kasse.vue
        * [ ] verband/protokoll.vue
        * [ ] verband/mitglieder.vue
        * [ ] verband/regeln.vue
        * [ ] verband/edit_name.vue
        * [ ] verband/edit_text.vue
        * [ ] verband/gebauede.vue
        * [ ] verband/bsr.vue
        * [ ] verband/home.vue
        * [ ] verband/news/edit.vue
        * [ ] credits.vue
        * [ ] profile/edit.vue
        * [ ] vehicle_group.vue
        * [ ] tasks.vue
        * [ ] assets/einsatz.vue
        * [ ] assets/task.vue
        * [ ] messages/new.vue
        * [ ] messages/conversation.vue
        * [ ] messages/system_message.vue
        * [ ] vehicle.vue
        * [ ] schoolings.vue
        * [ ] vehicle/stats.vue
        * [ ] freunde.vue
        * [ ] alliance_avatar.vue
        * [ ] lightbox.vue
        * [ ] note.vue
        * [ ] einsaetze.vue
        * [ ] fahrzeugfarbe.vue
        * [ ] verband.vue
        * [ ] coins/list.vue
        * [ ] chat.vue
        * [ ] aaos.vue
        * [ ] einsatz.vue
        * [ ] credits/daily.vue
        * [ ] credits/list.vue
        * [ ] credits/overview.vue
        * [ ] awards.vue
        * [ ] profile.vue
        * [ ] avatar.vue
        * [ ] alliances.vue
* [ ] **components** (2/22)
    * [ ] appstore.vue
    * [ ] enhanced-table.vue
    * [x] libraryOverview.vue [938a694](https://github.com/LSS-Manager/LSSM-V.4/commit/938a694)
    * [ ] lightbox.vue
    * [ ] leaflet-map.vue
    * [ ] anniversary.vue
    * [ ] setting/location/map.vue
    * [ ] setting/multi-select.vue
    * [ ] setting/hotkey.vue
    * [ ] setting/select.vue
    * [ ] setting/settings-appendable-list.vue
    * [ ] setting/number.vue
    * [ ] setting/textarea.vue
    * [ ] setting/toggle.vue
    * [ ] setting/text.vue
    * [ ] setting/location.vue
    * [ ] setting/slider.vue
    * [ ] setting/color.vue
    * [ ] settings.vue
    * [x] LoadingIndicator.vue [fb3de00](https://github.com/LSS-Manager/LSSM-V.4/commit/fb3de00)
    * [ ] arr.vue
    * [ ] setting.vue
* [ ] **src** (0/2)
    * [ ] LSSMV4.vue
    * [ ] LSSM-Menu.vue
